languageCode = "es"
languageName = "Spanish"
weight = 1
title = "PolymAG"

[params]
  displayName = "ES"
  isoCode = "es"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "img/logo1.png"
   #secondaryLogo = "img/bg.jpg"
   description = "Mi página"
   copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "PolymAG"
   image = "img/fondo1.jpg"
   headline = "PolymAG PRO es una empresa dedicada a la fabricación y venta de refacciones, soportes, amortiguadores de hule, caucho, una gama variada de elastómeros y poliuretano para maquinaria pesada, maquinaria ligera, servicio de vulcanizado y piezas especiales. Todo esto para industrias como son la minera, construcción, cementera, marítima, agropecuario, textil e industrias en general.\n\nEN HULE Y CAUCHO: Fabricación y venta de hule almorite, cañuela para cribas, raspadores de hule, rubber spring´s de hule, rodillos de hule, soportes de hule, aislantes de hule, coples de hule, servicio de vulcanizado de coples para compresores, Refacciones de hule para marcas como: BOMAG, CATERPILLAR, CASE, DYNAPAC, HYSTER, Ingersoll Rand, LIUGONG, MIKASA, MULLER, RAYGO, TAMPO, TEMATERRA, VOLVO, WACKER NEUSON, WIRTGEN | HAMM y piezas especializadas. \n\nPOLIURETANO: Fabricación y venta de placas de poliuretano en diferentes medidas, barras de poliuretano, topes de poliuretano para compuertas, soportes de poliuretano, fuelles de poliuretano, revestimientos de poliuretano para rodillos de arrastre, imprenta y minería, raspadores de poliuretano, impulsores de poliuretano, carcasas de poliuretano bujes de poliuretano, laterales de poliuretano para martillos hidráulicos, placa para pica de poliuretano para martillos hidráulicos, recubrimiento de poliuretano para tirantes para martillo hidráulico, limpiadores de poliuretano para tubería, topes de poliuretano, empaques de poliuretano, perfiles de poliuretano, rubber spring´s de poliuretano, recubrimiento de poliuretano de zapatas para perfiladores de asfalto, zapatas de poliuretano para pavimentadoras, zapatas de poliuretano para extendedoras de asfalto, recubrimiento de poliuretano para llantas de perfiladoras de asfalto, llantas de poliuretano para montacargas, llantas de poliuretano en general, rodajas de poliuretano y piezas especializadas en poliuretano en diferentes durezas (shore).  \n\nPRODUCTOS DE HULE: \nCañuela de hule cribas en diferentes medidas, \nHule almorite y Hule faldon en diferentes espesores, \nPerfiles y juntas de hule para mineria, \nRefacciones de hule para marcas como: BOMAG, CATERPILLAR, CASE, DYNAPAC, HYSTER, Ingersoll Rand, LIUGONG, MIKASA, MULLER, RAYGO, TAMPO, TEMATERRA, VOLVO, WACKER NEUSON, WIRTGEN | HAMM, \nSoportes / Amortiguadores de hule antivibratorios especializados , \nSuspensiones de hule para martillos hidráulicos , \nTacones de hule , \nRaspadores de hule, \nRubber Spring's de hule, \nRecubrimiento de rodillos de hule, \nEntre otros...\n\nPRODUCTOS DE POLIURETANO:\nRecubrimiento de llantas de poliuretano para pavimentadores \nRecubrimiento de llantas de poliuretano para perfiladora de asfalto \nRecubrimiento de llantas de poliuretano para montacargas\nRecubrimiento de llantas de poliuretano para patin de carga\nRecubrimiento en poliuretano de rodillos para arrastre, imprenta y minería\nRecubrimiento de poliuretano para tirantes para martillo hidrúlico\nPiezas de poliuretano para martillo hidraúlico en sus diferentes marcas.\nPlacas / Barras de poliuretano en diferentes medidas \nRodajas de poliuretano\nZapatas de poliuretano para pavimentadoras \nZapatas de poliuretado para perfiladoras\nZapatas de poliuretado para extendedoras de asfalto \nZapata de clip para Finisher.\nTopes de poliuretano\nSoportes / Amortiguadores de poliuretano\nFuelles de poliuretano\nRaspadores de poliuretano\nImpulsores de poliuretano\nCarcasas de poliuretano\nBujes de poliuretano\nLarerales de poliuretano para martillos hidraúlicos\nPlaca para pica de poliuretano para martillos hidraúlicos\nLimpiadores de poliuretano para tubería\nEmpaques de poliuretano\nPerfiles de poliuretano\nRubber Spring's de poliuretano\nEntre otros...\n\nSERVICIO DE VULCANIZADO\nServicio de vulcanizado para volante\nServicio de vulcanizado para sombrero / bacinica ATLAS\nServicio de vulcanizado para sombrero / bacinica\nEntre otros..."
   #bio = "PolymAG PRO"
   links = [
     { email = "mailto:ventas@polymag.com.mx" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
     { twitter = "https://twitter.com/username" },
     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
   ]
